# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__

'1.21.6'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
 a = np.array([1,2,3])
 msa = a.size * a.itemsize
 print(msa)

24


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [5]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [6]:
a = np.arange(10,50)

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [7]:
Arr = np.array([1,2,3,4,5,6,7,8,9])
Arr = Arr.reshape(3,3)
Arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [8]:
Arr = np.arange(9)
Arr = Arr.reshape(3,3)
Arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [9]:
a = np.array([1,2,0,0,4,0])
#a.nonzero()
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [11]:
arr = np.random.random(27).reshape(3,3,3)
arr.shape



(3, 3, 3)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [12]:
arr = np.random.randint(1, 1000 , 100).reshape(10,10)
print(arr.min())
print(arr.max())

6
991


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [13]:
a = np.random.random(30)
a.mean()

0.440246666703447

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [14]:
"""Answers are 
nan
true
False
nan
False"""

'Answers are \nnan\ntrue\nFalse\nnan\nFalse'

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [15]:
import numpy as np
arr = np.diag(np.arange(1,5),)
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [16]:
np.unravel_index(100 , (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [17]:
row_even =np.array([0, 1, 0, 1, 0, 1, 0, 1])
row_odd = np.array([1, 0, 1, 0, 1, 0, 1, 0])
arr_check_board1 = np.tile(row_even ,(4 , 1))
arr_check_board2 = np.tile(row_odd ,(4 , 1))

appended_arr = np.append(arr_check_board1 , arr_check_board2 , axis = 0)
print(appended_arr.shape)
a1 = np.flipud(appended_arr)
a1


(8, 8)


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [18]:
arr = np.random.randint(10 , size = 25).reshape(5,5)
#](arr)
minimum = np.min(arr)
maximum = np.max(arr)
sub = maximum -minimum
arr = (arr - minimum)/sub

print(arr)

[[1.         0.44444444 0.77777778 0.11111111 0.66666667]
 [0.33333333 0.88888889 0.         0.33333333 0.55555556]
 [0.77777778 0.55555556 0.55555556 0.33333333 0.66666667]
 [0.55555556 0.66666667 0.88888889 0.44444444 0.22222222]
 [0.44444444 0.11111111 0.66666667 0.22222222 0.22222222]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [19]:
arr1 = np.random.randint(10 , size = 15 ).reshape(5,3)
arr2 = np.random.randint(10 , size = 6).reshape(3,2)
mul_arr = arr1 @ arr2

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [20]:
arr = np.array([4,5,90,59,3,4,2,1,10,12,13])
arr_1= np.where((arr>2) & (arr<8))
np.delete(arr , list(arr_1))


array([90, 59,  2,  1, 10, 12, 13])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [21]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [22]:
z = np.array([1,2,3,4])
print(z**z)
print(2 << z >>2)
1j*z
print(z/1/1)

[  1   4  27 256]
[1 2 4 8]
[1. 2. 3. 4.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [23]:
np.array(0) / np.array(0)   #output nan
np.array(0) // np.array(0)  # 0
np.array([np.nan]).astype(int).astype(float)       # array 


<ipython-input-23-ac336ffe27da>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)   #output nan
<ipython-input-23-ac336ffe27da>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)  # 0


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [24]:
arr1 = np.array([1,2,3,7,8])
arr2 = np.array([1,3,90,9])
np.intersect1d(arr1 , arr2)


array([1, 3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [25]:
np.seterr(all="ignore")
np.errstate()  #parameters  for devide , over ,under , invalid 

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

No , given Expression return False  

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [26]:
np.datetime64()

numpy.datetime64('NaT')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [32]:
np.arange('2016-07','2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [33]:
A = np.array([[1,2,3] , [4,5,6,] ,[4,5,6] ])
B = np.array([[1,2,3] , [4,5,6,] ,[4,5,6] ])

add_AB = np.multiply(np.add(A , B) ,np.divide((np.negative(A) , np.array([2]))))
add_AB


TypeError: ignored

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [35]:
arr = np.array(np.random.random(size = 5))
#arr1 = arr % 
arr2 = np.floor(arr)
arr3 = np.ceil(arr)
arr4 = arr.astype('int')
arr5 = np.trunc(arr)

print(arr2)
print(arr3)
print(arr4)
print(arr5)


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 0 0 0 0]
[0. 0. 0. 0. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [36]:
arr_add = np.arange(0,5)
zero_arr = np.zeros((5,5))
arr_final =  zero_arr + arr_add
arr_final

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [37]:
import numpy as np
iterable = (x * x for x in range(6))
  
arr = np.fromiter(iterable, float)
  
print (arr)


[ 0.  1.  4.  9. 16. 25.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [38]:
vect = np.linspace(0,1,12 , endpoint=True)[1:-1]
vect


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [39]:
vect = np.random.randint(1, 100 , 10)
a = sort(vect)
a

array([ 2, 30, 34, 39, 44, 50, 58, 72, 87, 99])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [40]:
arr = np.array(np.arange(100))
sum = np.add.reduce(arr)
print(sum)

4950


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [41]:
arr1 = np.array(np.arange(25)).reshape(5,5)
arr2 = np.array(np.random.randint(1 ,25 ,25)).reshape(5,5)
print(np.allclose(arr1, arr2))
print(np.array_equal(arr1 , arr2))

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [42]:
arr = np.ones(10)
arr.flags.writeable = False
#if we try  to change any element of array it will through an error

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [43]:
arr = np.random.randint(1 , 10 , 20).reshape(10,2)

x = arr[: , 0]
y = arr[: ,1]

squ = np.sqrt(x ** 2 + y ** 2).reshape(10,1)
theta = np.arctan2(y, x).reshape(10,1)

final_arr = np.concatenate((squ , theta), axis = 1)
print(final_arr)


[[6.70820393 1.10714872]
 [4.12310563 0.24497866]
 [5.83095189 1.03037683]
 [7.28010989 1.29249667]
 [4.24264069 0.78539816]
 [5.83095189 0.5404195 ]
 [4.47213595 0.46364761]
 [7.28010989 1.29249667]
 [4.12310563 0.24497866]
 [7.07106781 1.42889927]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [44]:
vect = np.random.random(10)
maxi = np.argmax(vect)
vect[maxi] = 0
vect

array([0.72152981, 0.        , 0.61176412, 0.46725554, 0.12024755,
       0.36500072, 0.84558732, 0.44258415, 0.02309452, 0.66358176])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [45]:
import numpy as np
data_types = [np.int8, np.int32, np.int64]
for each in data_types:
   print(np.iinfo(each).min)
   print(np.iinfo(each).max)
data_types = [np.int64]
for each in data_types:
   print(np.finfo(each).min)
   print(np.finfo(each).max)
   print(np.finfo(each).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


ValueError: ignored

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [47]:
np.set_printoptions(threshold=float("inf"))
arr = np.ones((5,5))
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [48]:
import numpy as np
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

50


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [49]:
vect = np.random.random((100,2))
x = np.atleast_2d(vect[:, 0])
y = np.atleast_2d(vect[: ,1])

sqr = np.sqrt((x-x.T)**2 + (y-y.T)**2)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [50]:
import numpy as np
arr = (np.random.rand(10)* 200 ).astype(np.int32 , copy=False)
arr.dtype

dtype('int32')

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [51]:
from io import StringIO
s = StringIO("1, 2, 3, 4, 5,6,  ,  , 7, 8,  , 9,10,11")
arr = np.genfromtxt(s , delimiter = ',' , dtype = np.int)
arr

<ipython-input-51-798a56872e17>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.genfromtxt(s , delimiter = ',' , dtype = np.int)


array([ 1,  2,  3,  4,  5,  6, -1, -1,  7,  8, -1,  9, 10, 11])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [52]:
arr = np.arange(24).reshape(6,4)

for i,j in np.ndenumerate(arr):
  print(i, j)

for i in np.ndindex(arr.shape):
  print(i , arr[i])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
(4, 0) 16
(4, 1) 17
(4, 2) 18
(4, 3) 19
(5, 0) 20
(5, 1) 21
(5, 2) 22
(5, 3) 23
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
(4, 0) 16
(4, 1) 17
(4, 2) 18
(4, 3) 19
(5, 0) 20
(5, 1) 21
(5, 2) 22
(5, 3) 23


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [53]:
arr = np.array([[[1,2,3], [4,5,6]] , [[7,8,9],[10,11,12]]])
p = 3
np.put(arr, np.random.choice(range(12) ,p ,replace = True) ,100)
arr

array([[[  1,   2,   3],
        [  4, 100,   6]],

       [[  7, 100,   9],
        [ 10,  11,  12]]])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [54]:
arr = np.random.randint(1,10 , 9).reshape(3,3)
print(arr)
arr = arr - arr.mean(axis = 1 , keepdims = True)
arr

[[6 1 1]
 [7 9 9]
 [3 7 7]]


array([[ 3.33333333, -1.66666667, -1.66666667],
       [-1.33333333,  0.66666667,  0.66666667],
       [-2.66666667,  1.33333333,  1.33333333]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [55]:
Z = np.random.randint(0,13,(3,4))
print(Z)
print(Z[Z[:,1].argsort()])   #sort array according to 1st column 

[[ 0  9 10 12]
 [ 9  9  9  1]
 [11 11  8  9]]
[[ 0  9 10 12]
 [ 9  9  9  1]
 [11 11  8  9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [56]:
arr = np.random.randint(0,13,(3,4))
print((~arr.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [57]:
arr = (np.random.random(10)*100 ).reshape(2,5)
print(arr)
m = arr.flat[np.abs(arr).argmin()]
print(m)

[[34.22818022 16.73223059 85.96000482  4.89448247 48.20695588]
 [ 8.15307203 96.92827423  9.69913171 63.65673637 58.78315107]]
4.894482466845673


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [58]:
arr1 = np.random.randint(1,5 ,3)
arr2 = np.random.randint(1,5,(3,1))
it = np.nditer([arr1,arr2,None])
print(it)
for x,y,z in it: 
  z[...] = x + y
print(it.operands[2])

[[7 6 7]
 [6 5 6]
 [5 4 5]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [59]:
arr = np.random.randint(1,20, 10)
print(arr)
index_val = np.random.randint(0,len(arr),10)
np.add.at(arr,index_val,1)
print(arr)

[10  9  8 11 15 14 10 13  4  6]
[11 10  8 12 16 15 13 14  4  7]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [60]:
arr = np.random.randint(1,200 ,(3,2,3,2))
print(arr)
print(arr.sum(axis = (-2,-1)))

[[[[ 67  91]
   [  3 181]
   [123   6]]

  [[158  89]
   [ 40 122]
   [ 18  34]]]


 [[[ 88 184]
   [199  78]
   [173   6]]

  [[ 50 190]
   [195 184]
   [ 13  72]]]


 [[[130 107]
   [ 18  42]
   [175  92]]

  [[ 99 195]
   [114 115]
   [134  57]]]]
[[471 461]
 [728 704]
 [564 714]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [61]:
D = np.random.uniform(0,1,10)
S = np.random.randint(0,10,10)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.19475741        nan 0.28464284 0.37906546 0.26689614 0.10886903
        nan 0.34669673 0.39020611 0.37577219]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [62]:
arr1 = np.random.randint(0,9,(4,4))
arr2 = np.random.randint(0,20,(4,4))
dot_diagonal = np.diag(np.dot(arr1,arr2))
print(dot_diagonal)

[292 148 126  84]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [63]:
import numpy as np
arr = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(arr) + (len(arr)-1)*(nz))
Z0[::nz+1] = arr
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [64]:
arr1 = np.random.random(75).reshape(5,5,3)
arr2 = np.random.randint(1,10,25).reshape(5,5)
print(arr1 * arr2[:,:,None])


[[[2.62603615 6.88867525 0.37914596]
  [4.92488149 0.7611517  4.58213051]
  [4.98478201 1.99180771 1.85851065]
  [0.96513061 0.62685423 0.88686489]
  [4.81838745 4.81014367 7.8081846 ]]

 [[0.97043914 0.68252425 0.50529748]
  [0.54762388 2.16338188 4.48268049]
  [2.91872918 5.6786227  4.97461971]
  [7.74778893 1.01847944 2.37338129]
  [2.30629354 2.56709477 2.05638397]]

 [[5.88243826 3.34668914 5.21147968]
  [3.31308629 2.34291145 5.18950251]
  [0.73132335 0.32035879 1.94633484]
  [0.99306759 0.33685849 0.56330454]
  [1.55606304 0.35003766 6.29122906]]

 [[0.50489981 0.26385422 1.45450472]
  [2.95279904 0.73412154 5.43174088]
  [7.81209801 2.20000968 2.38396699]
  [2.55961288 5.52245407 3.67897844]
  [0.181027   0.12501389 0.64750883]]

 [[0.78785875 1.8629631  0.66800607]
  [3.80499964 0.03834394 2.54532696]
  [0.31692679 0.54036934 1.7276167 ]
  [4.29816931 6.08918874 5.26753092]
  [1.96139761 1.46957832 0.40925924]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [65]:
arr = np.arange(1,11).reshape(5,2)
print(arr)
arr[[0,3]]= arr[[3,0]]
arr

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


array([[ 7,  8],
       [ 3,  4],
       [ 5,  6],
       [ 1,  2],
       [ 9, 10]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [66]:
import numpy as np
arr  = np.random.randint(0,10 ,20)
print(arr)
np.logical_not(arr , out=arr)

arr1 = np.random.uniform(-1.0 , 1 ,10)
print(arr1)
np.negative(arr1 , out = arr1)

[4 6 5 6 1 8 9 1 6 8 6 4 4 2 9 9 1 6 7 7]
[-0.21796048  0.15891862  0.20209483  0.48632627 -0.07686904  0.01477291
  0.60627219  0.19318726  0.38915339 -0.84158042]


array([ 0.21796048, -0.15891862, -0.20209483, -0.48632627,  0.07686904,
       -0.01477291, -0.60627219, -0.19318726, -0.38915339,  0.84158042])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [67]:
import numpy as np
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
arr_shape = (11,4)
arr_stride = (Z.itemsize , Z.itemsize)
np.lib.stride_tricks.as_strided(Z , arr_shape , arr_stride)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [68]:
arr= np.array([1,2,3,4,5,5,5,7,7,9,10,10,10,10,10])
np.bincount(arr)

array([0, 1, 1, 1, 1, 3, 0, 2, 0, 1, 5])

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [69]:
import numpy as np
arra1 = np.random.randint(0,5,(10,10))
print("Original arrays:")
print(arra1)
n = 4
i = 1 + (arra1.shape[0]-3)
j = 1 + (arra1.shape[1]-3)
result = np.lib.stride_tricks.as_strided(arra1, shape=(i, j, n, n), strides = arra1.strides + arra1.strides)
print("\nContiguous 4x4 blocks:")
print(result)


Original arrays:
[[3 4 4 4 4 2 0 2 1 4]
 [1 2 0 1 2 0 4 4 4 3]
 [0 0 3 4 3 0 0 2 4 3]
 [4 2 4 4 2 2 0 4 4 1]
 [3 0 2 3 3 1 0 1 3 2]
 [0 3 2 4 1 0 4 2 4 1]
 [0 4 4 1 0 3 3 4 2 3]
 [0 1 2 2 3 2 2 0 2 0]
 [2 2 4 4 0 0 3 1 0 1]
 [2 4 1 2 4 0 1 2 2 3]]

Contiguous 4x4 blocks:
[[[[                   3                    4                    4
                       4]
   [                   1                    2                    0
                       1]
   [                   0                    0                    3
                       4]
   [                   4                    2                    4
                       4]]

  [[                   4                    4                    4
                       4]
   [                   2                    0                    1
                       2]
   [                   0                    3                    4
                       3]
   [                   2                    4                    4
        

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [70]:
N = 100
arr = np.random.randint(1,100 , 10)
idx = np.random.randint(0, arr.size, (N, arr.size))
means = arr[idx].mean(axis=1)
Interval = np.percentile(means, [2.5, 97.5])
print(Interval)

[36.9425 71.8025]
